base_dir:
  type: Path
  required: true
  help: Directory containing the raw dataset.
data_dir:
  type: Path
  required: true
  help: Directory to save the processed Segger dataset.
sample_type:
  type: str
  default: null
  help: The sample type of the raw data, e.g., "xenium" or "merscope".
scrnaseq_file:
  type: str
  default: null
  help: Name of the scRNA-seq file.
celltype_column:
  type: str
  default: null
  help: Column name for cell type annotations in the scRNAseq file.
k_bd:
  type: int
  default: 3
  help: Number of nearest neighbors for boundary nodes.
dist_bd:
  type: float
  default: 15.
  help: Maximum distance for boundary neighbors.
k_tx:
  type: int
  default: 3
  help: Number of nearest neighbors for transcript nodes.
dist_tx:
  type: float
  default: 5.
  help: Maximum distance for transcript neighbors.
tile_size:
  type: int
  default: null
  help: If provided, specifies the size of the tile. Overrides `tile_width` and `tile_height`.
tile_width:
  type: int
  default: null
  help: Width of the tiles in pixels. Ignored if `tile_size` is provided.
tile_height:
  type: int
  default: null
  help: Height of the tiles in pixels. Ignored if `tile_size` is provided.
neg_sampling_ratio:
  type: float
  default: 5.
  help: Ratio of negative samples.
frac:
  type: float
  default: 1.
  help: Fraction of the dataset to process.
val_prob:
  type: float
  default: 0.1
  help: Proportion of data for use for validation split.
test_prob:
  type: float
  default: 0.2
  help: Proportion of data for use for test split.
n_workers:
  type: int
  default: 1
  help: Number of workers for parallel processing.
