dataset_type: xenium
dataset_dir: data_raw/xenium
data_dir: data_tidy/pyg_datasets
sample_tag: Xenium_FFPE_Human_Breast_Cancer_Rep1
transcripts_file: transcripts.parquet
boundaries_file: nucleus_boundaries.parquet
min_qv: 20
file_format: parquet

# Parameters for saving the dataset
x_size: 200
y_size: 200
d_x: 150
d_y: 150
margin_x: 20
margin_y: 20
compute_labels: true
r_tx: 5
val_prob: 0.1
test_prob: 0.2
neg_sampling_ratio_approx: 5
sampling_rate: 1
workers: 1

# Receptive field parameters
k_bd: 3
dist_bd: 15
k_tx: 10
dist_tx: 3

# Method and GPU usage
method: kd_tree
gpu: false
