data_dir: 
  type: str
  required: true
  help: "Directory to store raw and processed data."

sample_dir: 
  type: str
  required: true
  help: "Path to spatial transcriptomics sample."

sample_type: 
  type: str
  default: null
  help: "Type of spatial transcriptomics sample (e.g., 'xenium')."

tile_size:
  type: int
  default: 100000
  help: "Maximum no. transcripts per tile."

tile_width:
  type: int
  default: null
  help: "Width of each tile."

tile_height: 
  type: int
  default: null
  help: "Height of each tile."

k_bd: 
  type: int
  default: 3
  help: "Number of nearest neighbors for nuclei."

dist_bd: 
  type: float
  default: 4
  help: "Distance threshold for nuclei."

k_tx: 
  type: int
  default: 3
  help: "Number of nearest neighbors for transcripts."

dist_tx: 
  type: float
  default: 1
  help: "Distance threshold for transcripts."

val_prob: 
  type: float
  default: 0.1
  help: "Probability of assigning a tile to the validation set."

test_prob: 
  type: float
  default: 0.1
  help: "Probability of assigning a tile to the test set."

sampling_rate: 
  type: float
  default: 1
  help: "Rate of sampling tiles."

neg_sampling_ratio:
  type: float
  default: 5
  help: "Ratio of negative edges to sample for training."

gene_embedding_weights:
  type: str
  default: null
  help: "Path to CSV containing gene embedding weights. See Segger docs."

n_workers: 
  type: int
  default: 1
  help: "Number of workers for parallel processing."
