segger_data_dir:
  type: Path
  required: true
  help: Directory containing the processed Segger dataset.
models_dir:
  type: Path
  required: true
  help: Directory containing the trained models.
benchmarks_dir:
  type: Path
  required: true
  help: Directory to save the segmentation results.
transcripts_file:
  type: str
  required: true
  help: Path to the transcripts file.
batch_size:
  type: int
  default: 1
  help: Batch size for processing.
num_workers:
  type: int
  default: 1
  help: Number of workers for data loading.
model_version:
  type: int
  default: 0
  help: Model version to load.
save_tag:
  type: str
  default: "segger_embedding_1001_0.5"
  help: Tag for saving segmentation results.
min_transcripts:
  type: int
  default: 5
  help: Minimum number of transcripts for segmentation.
cell_id_col:
  type: str
  default: "segger_cell_id"
  help: Column name for cell IDs.
use_cc:
  type: bool
  default: false
  help: Use connected components if specified.
knn_method:
  type: str
  default: "cuda"
  help: Method for KNN computation.
file_format:
  type: str
  default: "anndata"
  help: File format for output data.
k_bd:
  type: int
  default: 4
  help: K value for boundary computation.
dist_bd:
  type: float
  default: 12
  help: Distance for boundary computation.
k_tx:
  type: int
  default: 5
  help: K value for transcript computation.
dist_tx:
  type: float
  default: 5
  help: Distance for transcript computation.
