name: segger_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - tqdm>=4.61.0
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - pytorch-lightning>=1.3.0
  - torchmetrics>=0.5.0
  - scanpy>=1.8.0
  - squidpy>=1.1.0
  - adjusttext>=0.8.0
  - scikit-learn>=0.24.0
  - geopandas>=0.9.0
  - shapely>=1.7.0
  - pip
  - pip:
    - pyg_lib>=0.0.0
    - torch_scatter>=2.0.0
    - torch_sparse>=0.6.0
    - torch_cluster>=1.5.9
    - torch_spline_conv>=1.2.0