name: segger_dev
channels:
  - defaults
  - conda-forge
dependencies:
  # - python=3.11
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - tqdm>=4.61.0
  - pytorch>=2.0.0
  - torchvision>=0.10.0
  - pytorch-lightning>=1.3.0
  - torchmetrics>=0.5.0
  - scanpy>=1.9.3
  - squidpy=1.2.0
  - adjustText>=0.8
  - scikit-learn>=0.24.0
  - geopandas>=0.9.0
  - shapely>=1.7.0
  # - pyg>=2.2.0
  - torch-scatter>=2.1.2
  - torch-sparse>=0.6.18
  - torch-cluster>=1.6.3
  - pip:
      - setuptools>=42
      - wheel
      - pytest
      - black
      - flake8