name: segger
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.5.3
  - numpy=1.23.5
  - anndata=0.8.0
  - scipy=1.10.1
  - scanpy=1.9.1
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - squidpy=1.1.1
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-lightning=2.0.0
  - torch-geometric=2.2.0
  - torchmetrics=0.11.4
  - zarr=2.14.1
  - tqdm=4.65.0
  - pathlib=1.0.1
  - scikit-learn=1.2.2
  - adjustText=0.8.3
  - pip
  - pip:
      - argparse==1.4.0
      - -e .
