name: segger
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.21.2
  - pandas=1.3.3
  - scipy=1.7.1
  - matplotlib=3.4.3
  - scikit-learn=0.24.2
  - pytorch=1.9.0
  - pyg=2.0.2
  - anndata=0.7.6
  - geopandas=0.9.0
  - shapely=1.7.1
  - tqdm=4.62.2
  - requests=2.26.0
  - sphinx=4.2.0
  - sphinx-rtd-theme=1.0.0
  - nbsphinx=0.8.7
  - sphinxcontrib-napoleon=0.7
  - jupyter=1.0.0
  - pip:
    - torch-geometric==2.0.2
