site_name: Segger Documentation
site_description: "Fast and accurate cell segmentation for single-molecule spatial omics"
site_author: Elyas Heidari
repo_url: https://github.com/EliHei2/segger_dev
theme:
  name: material
  features:
    - navigation.tabs
  logo: images/logo.png
  favicon: images/logo.png
  font:
    text: ubuntu
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.tabs.link
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to system preference
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home: index.md
  - Getting Started:
      - Overview: user_guide/index.md
      - Installation: installation.md
      - Dataset Creation: user_guide/data_creation.md
      - Training: user_guide/training.md
      # - Examples: user_guide/examples.md
  - CLI: api/cli/index.md
  - API Reference:
      - Overview: api/index.md
      - Segger:

          - Models: api/models/index.md
          - Data: api/data/index.md
          - Training: api/training/index.md
          - Validation: api/validation/index.md
          - Prediction: api/prediction/index.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            headings: true          # Add structured headings for sections like Parameters
            show_signature: true    
            show_source: true
            paths:
            search_path: ["src"]
            show_root_heading: true
            heading_level: 3
  - mkdocs-jupyter:
      include_source: True

markdown_extensions:
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  # - pymdownx.tabs
  - pymdownx.critic
  - pymdownx.tasklist
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.betterem
  - pymdownx.tilde
  - admonition        # Adds better note formatting for parameters, warnings, etc.
  - codehilite        # Syntax highlighting for code
  - toc               # Table of contents for better navigation
  - pymdownx.superfences  # Handles complex nested code blocks or fenced content
  - pymdownx.details   
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

extra_css:
  - css/extra.css
  - https://cdn.jsdelivr.net/npm/katex@0.13.11/dist/katex.min.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js