from setuptools import setup, find_packages

setup(
    name="segger",
    version="0.1.0",
    description="Fast and accurate cell segmentation for single-molecule spatial omics",
    author="Elyas Heidari",
    author_email="elyas.heidari@dkfz-heidelberg.de",
    license="MIT",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    python_requires=">=3.10",
    keywords=["segmentation", "deep learning", "pytorch", "geometric deep learning"],
    install_requires=[
        "torch>=2.0.0",
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "scipy>=1.7.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "tqdm>=4.61.0",
        "torchvision>=0.10.0",
        "lightning>=1.9.0",
        "torchmetrics>=0.5.0",
        "scanpy>=1.9.3",
        "squidpy==1.2.0",
        "adjustText>=0.8",
        "scikit-learn>=0.24.0",
        "geopandas>=0.9.0",
        "shapely>=1.7.0",
        "path>=17.0.0",
        "pyarrow>=17.0.0",
        "torch-geometric>=2.2.0",
        "dask_geopandas>=0.4.0"
    ],
    extras_require={
        "gpu": [
            "cuml>=21.08",
            "cudf>=21.08",
            "cugraph>=21.08",
            "cuspatial>=21.08",
            "faiss-cpu>=1.7.0",
            "faiss-gpu>=1.7.0"
        ],
        "torch-geometric": [
            "torch-scatter>=2.1.2",
            "torch-sparse>=0.6.18",
            "torch-cluster>=1.6.3",
        ],
        "multiprocessing": ["multiprocessing"],
        "dev": [
            "pytest",
            "black",
            "flake8",
            "pre-commit",
            "twine>=4.0.2",
        ],
        "docs": [
            "docutils>=0.8,!=0.18.*,!=0.19.*",
            "sphinx>=4.1",
            "sphinx-book-theme>=1.0.0",
            "myst-nb",
            "myst-parser",
            "sphinxcontrib-bibtex>=1.0.0",
            "sphinx-autodoc-typehints",
            "sphinx_rtd_theme",
            "sphinxext-opengraph",
            "sphinx-copybutton",
            "sphinx-design",
            "sphinx-hoverxref",
            "ipykernel",
            "ipython",
            "pandas",
        ],
        "tests": [
            "pytest",
            "coverage",
        ],
    },
    url="https://github.com/EliHei2/segger_dev",
    project_urls={
        "Bug Tracker": "https://github.com/EliHei2/segger_dev/issues",
        "Documentation": "https://EliHei2.github.io/segger_dev",
        "Source Code": "https://github.com/EliHei2/segger_dev",
        "Homepage": "https://EliHei2.github.io/segger_dev",
        "Repository": "https://github.com/EliHei2/segger_dev",
    },
    packages=find_packages(where="src"),
    package_dir={"": "src"},
)
