data_dir: 
  type: str
  required: true
  help: "Path to the data loader directory"

model_dir: 
  type: str
  required: true
  help: "Root directory for logs and model checkpoints"

batch_size_train: 
  type: int
  default: 4
  help: "Batch size for training"

batch_size_val: 
  type: int
  default: 4
  help: "Batch size for validation"

init_emb: 
  type: int
  default: 8
  help: "Initial embedding size"

hidden_channels: 
  type: int
  default: 64
  help: "Number of hidden channels"

out_channels: 
  type: int
  default: 16
  help: "Number of output channels"

heads: 
  type: int
  default: 4
  help: "Number of attention heads"

aggr: 
  type: str
  default: "sum"
  help: "Aggregation method"

accelerator: 
  type: str
  default: "cuda"
  help: "Type of accelerator"

strategy: 
  type: str
  default: "auto"
  help: "Training strategy"

precision: 
  type: str
  default: "16-mixed"
  help: "Precision mode"

devices: 
  type: int
  default: 4
  help: "Number of devices"

epochs: 
  type: int
  default: 100
  help: "Number of epochs"
