create_dataset:
  # Input filepaths
  transcripts_parquet: '/data1/peerd/moormana/GitHub/EliHei2/segger_dev/.dev/data/xenium_human_colon_healthy/ist_dataset/transcripts_geo.parquet'
  boundaries_parquet: '/data1/peerd/moormana/GitHub/EliHei2/segger_dev/.dev/data/xenium_human_colon_healthy/ist_dataset/nucleus_boundaries_geo.parquet'
  # Input fields
  transcripts_feature_name: 'feature_name'
  transcripts_cell_id: 'nucleus_boundaries_id'
  transcripts_x: 'x_location'
  transcripts_y: 'y_location'
  # Graph params
  transcripts_k: 20
  transcripts_dist: 5
  boundaries_k: 3
  boundaries_dist: 20
  # Tiling params
  max_cells_per_tile: 500
  tile_margin: 10
  fraction_train: 0.7
  fraction_test: 0.2
  fraction_val: 0.1
  # Ouput options
  save_dir: '/data1/peerd/moormana/GitHub/EliHei2/segger_dev/.dev/data/xenium_human_colon_healthy/test/segger_dataset'
  n_workers: 8
train:
  # Input filepaths
  gene_embedding_csv: null
  # Model params
  in_channels: 16
  hidden_channels: 32
  out_channels: 32
  n_mid_layers: 4
  n_heads: 3
  # Data loader params
  n_workers: 8
  batch_size: 2
  max_transcripts_k: null
  max_transcripts_dist: null
  negative_edge_sampling_ratio: 3
  # Training params
  learning_rate: 0.001
  n_epochs: 50
  # Output options
  root_dir: '/data1/peerd/moormana/GitHub/EliHei2/segger_dev/.dev/data/xenium_human_colon_healthy/test/segger_models'